api/urls.py
from django.urls import path
from rest_framework import routers
from .views import ProductViewSet, ContractorViewSet, OperationViesSet, StorageItemViewSet, DocumentViewSet, \
    DocumentItemViewSet, contractor_categories, apply_document, unapply_document, remove_marked_objects, \
    import_products, consolidated_report, motion_report

app_name = 'api'

urlpatterns = [
    path('contractor_categories/', contractor_categories, name='contractor_categories'),
    path('apply_document/<int:document_id>/', apply_document, name='apply_document'),
    path('unapply_document/<int:document_id>/', unapply_document, name='unapply_document'),
    path('remove_marked_objects/', remove_marked_objects, name='remove_marked_objects'),
    path('import_products/', import_products, name='import_products'),
    path('consolidated_report/', consolidated_report, name='consolidated_report'),
    path('motion_report/', motion_report, name='motion_report')
]

router = routers.SimpleRouter()
router.register('products', ProductViewSet, basename='products')
router.register('contractors', ContractorViewSet, basename='contractors')
router.register('operations', OperationViesSet)
router.register('documents', DocumentViewSet, basename='documents')
router.register('document_items', DocumentItemViewSet, basename='document_items')
router.register('storage_items', StorageItemViewSet, basename='storage_items')
urlpatterns.extend(router.urls)

hostel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main.views import Login, Logout


urlpatterns = [
    path('admin/', admin.site.urls),
    path("hostel_app/", include("hostel_app.urls", namespace="hostel_app")),
    path('accounts/',include('allauth.urls')),
    #path('restaurant/', include('hostel_app.urls', namespace='restaurant'))
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('api/', include('api.urls')),
    path('storage', include('main.urls'))
   
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hostel_app/urls.py
from django.urls import path
from hostel_app.views import HostelAppView, HostelAppView2, restaurant_view, room_id_view
from . import views


app_name = 'hostel_app'

urlpatterns=[
    path('', HostelAppView.as_view(), name='hostel_app'),
    path('room/', HostelAppView2.as_view(), name='rooms'),
    path('booking/', views.book_room, name='booking'),
    path('fitness/', views.fitness_view, name='fitness'),
    path('restaurant/', restaurant_view, name='restaurant'),
    path('<int:pk>/', room_id_view, name='details'),
    path('profile_user/',  views.view_profile, name='profile_user'),
    path('profile_user/edit_profile/', views.edit_profile, name='edit_profile'),
    path('profile_user/create_profile/', views.create_profile, name='create_profile'),
    path('profile_user/create_profile/success', views.success, name='success'),
   
]

main/urls.py
from django.urls import path
from .views import index, products, contractors, documents, operations, storage_items, products_to_xls, \
    contractors_to_xls, remove_marked_objects, import_products, consolidated_report, motion_report

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('products/', products, name='products'),
    path('contractors/', contractors, name='contractors'),
    path('documents/', documents, name='documents'),
    path('operations/', operations, name='operations'),
    path('storage_items/', storage_items, name='storage_items'),
    path('products_to_xls/', products_to_xls, name='products_to_xls'),
    path('contractors_to_xls/', contractors_to_xls, name='contractors_to_xls'),
    path('remove_marked_objects/', remove_marked_objects, name='remove_marked_objects'),
    path('import_products/', import_products, name='import_products'),
    path('consolidated_report/', consolidated_report, name='consolidated_report'),
    path('motion_report/', motion_report, name='motion_report')
]

hostel_app/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User



class Guest(models.Model):
    name  = models.CharField(max_length=20,verbose_name="ФИО")
    age   = models.IntegerField(default=20, verbose_name="Возраст")
    phone = models.CharField(max_length=20, verbose_name="Номер телефона")
    score = models.IntegerField(default=20, verbose_name="Номер счёта")

    def __str__(self) -> str:
        return self.name
    

class Room(models.Model):
    name = models.CharField(max_length=128, verbose_name="Название")
    description = models.TextField(blank=False, verbose_name="Описание")
    price = models.FloatField(default=1000.0, verbose_name="Цена")
    is_booked = models.BooleanField(default=False, verbose_name="Есть в книге?")
    img = models.ImageField(upload_to="%Y/%m/%d/", verbose_name="Изображение") 
    bed = models.IntegerField(default=1, verbose_name='Кровать кол-во')
    bath = models.IntegerField(default=1, verbose_name='Душ кол-во')
    hottest = models.BooleanField(default=False, verbose_name='Является горячим предложением')

    def __str__(self):
        return self.name

class Booking(models.Model):
    status_choices = (
              ('ожидание', 'Ожидание'),
              ('подтверждено', 'Подтверждено'),
              ('отменено', 'Отменено'),
        )
    name  = models.CharField(max_length=40,verbose_name="ФИО")
    phone = models.CharField(max_length=11, verbose_name="Номер телефона")
    room          = models.ForeignKey(Room, on_delete=models.CASCADE, verbose_name="Номер")
    num_of_guest  = models.IntegerField(default=1, verbose_name="Кол-во взрослых")
    num_of_child  = models.IntegerField(default=1, verbose_name="Кол-во детей")
    checkin_date  = models.DateTimeField(default=timezone.now, verbose_name="Дата заселения")
    checkout_date = models.DateTimeField(default=timezone.now, verbose_name="Дата выселения")
    status = models.CharField(max_length=255, verbose_name='Статус', choices=status_choices, default='ожидание')
    is_checkout   = models.BooleanField(default=True, verbose_name="Проверено")
    services   = models.BooleanField(default=True, verbose_name="Доп.услуги")

    def __str__(self) -> str:
        return self.name
   
    
class Images(models.Model):
    model_img = models.ImageField(upload_to='static/images')
    
    
class Staff(models.Model):
    name  = models.CharField(max_length=200,verbose_name="ФИО")
    img = models.ImageField(upload_to="%Y/%m/%d/", verbose_name="Изображение") 
    data = models.DateField( verbose_name="Дата рождения")
    passport =  models.CharField(max_length=10,verbose_name="Паспортные данные")
    address =  models.CharField(max_length=100,verbose_name="Адрес")
    phone = models.CharField(max_length=20, verbose_name="Номер телефона")
    post =  models.CharField(max_length=100,verbose_name="Должность")
    login =  models.CharField(max_length=100,verbose_name="Логин")
    password = models.CharField(max_length=20, verbose_name="Пароль")
    
    def __str__(self) -> str:
        return self.name
    
class Duty(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE, verbose_name="Сотрудник")
    day = models.CharField(max_length=11,verbose_name="День недели")


class Reservation(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    guest = models.ForeignKey(Guest, on_delete=models.CASCADE)
    data = models.DateField()

class Subscriber(models.Model):
    email = models.EmailField(unique=True, verbose_name='Почта')

    
    

hostel_app/forms.py
from django import forms
from hostel_app.models import Booking, Subscriber
from profile_user.models import Profile

class RoomSearchForm(forms.Form):
    search = forms.CharField(max_length=128)
    
    
class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        exclude = ('is_checkout','services','status', 'user')
        
        
    
        
        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'profile_picture','location', 'birth_date']



class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ['email']

hostel_app/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from hostel_app.forms import RoomSearchForm, BookingForm
from hostel_app.models import Room, Staff, Booking
from django.core.paginator import Paginator
from profile_user.models import Profile
from .forms import BookingForm, ProfileForm


class HostelAppView(ListView):
    model = Room
    context_object_name = 'rooms'
    template_name = 'rooms.html'

    def get_queryset(self):
        return self.model.objects.filter(hottest=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['staffs'] = Staff.objects.all()
        context['form'] = SubscriberForm()
        return context

    def post(self, request):
        form = SubscriberForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'subscribed.html')
        else:
            queryset = self.get_queryset()
            staff = Staff.objects.all()
            return render(request, self.template_name, context={'rooms': queryset, 'staffs': staff, 'form': form})
        
   

class HostelAppView2 (ListView):
   model = Room
   context_object_name = 'rooms'
   template_name = 'rooms2.html'
   paginate_by = 3
   
   def get_context_data(self, *, object_list=None, **kwargs):
       context = super().get_context_data(object_list=object_list, **kwargs)
       context['object-count'] = self.model.objects.count()
       paginator = Paginator(self.model.object_list, self.paginate_by)
       try:
           page = self.request.GET.get('page')
       except:
           page = 1
           
       try:
           context[self.context_object_name] = paginator.page(page)
       except:
           context[self.context_object_name] = paginator.page(1)
           
       context['object-count'] = self.model.objects.count()
       context['paginator'] = paginator
       return context
  
   def get_context_data(self,*,object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        
        form = RoomSearchForm(self.request.GET)
        if form.is_valid():
            pass
        
        else:
            form = RoomSearchForm()
            
        context['form'] = form
        return context
        
   def get(self, request, *args, **kwargs):
       form = RoomSearchForm(self.request.GET)
       if form.is_valid():
           cd = form.cleaned_data
           rooms = self.model.objects.filter(name__icontains=cd['search'])
       else:
           rooms = self.model.objects.all()
       return render(request, self.template_name, self.get_context_data(object_list=rooms))
   
    
   
class StaffView (ListView):
   model = Staff
   context_object_name = 'staffs'
   template_name = 'rooms.html'
   
   
def restaurant_view(request):
    context = {'page':'restaurant'}
    return render(request, 'restaurant.html',context)

   
def fitness_view(request):
    context = {'page':'fitness'}
    return render(request, 'fitness.html',context)




   
def room_id_view(request, pk):
    pk = get_object_or_404(Room, pk=pk)
    booking = Booking.objects.all()
    if request.method=="POST": 
        form = BookingForm(request.POST) 
        if form.is_valid(): 
            booking =  form.save(commit=False) 
            booking.rooms = pk 
            booking.save() 
            form = BookingForm() 
    else:
        form = BookingForm()
    context = {"pk": pk,'page':'rooms', 'booking_list':booking, 'form':form}
    return render(request, "rooms_details.html", context)



def book_room(request):
    booking = Booking.objects.all()
    if request.method=="POST": 
        form = BookingForm(request.POST) 
        if form.is_valid(): 
            booking =  form.save(commit=False) 
            booking.save() 
            form = BookingForm() 
    else:
        form = BookingForm()
    context = {'page':'rooms', 'booking_list':booking, 'form':form, }
    return render(request, "booking.html", context)

def create_profile(request):
    try:
        profile = Profile.objects.get(user=request.user)
        return render(request, 'profile/success.html',{'profile': profile})
    except Profile.DoesNotExist:
        pass

    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return render(request, 'profile/success.html', {'profile': profile})
    else:
        form = ProfileForm()
    return render(request, 'profile/create_profile.html', {'form': form})


def success(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'profile/success.html', {'profile': profile})


def view_profile(request):
    profile = Profile.objects.get(user=request.user)
   
    return render(request, 'profile/profile_user.html', {'profile': profile})

def edit_profile(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return render(request, 'profile/success.html', {'profile': profile})
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'profile/edit_profile.html', {'form': form})



from .forms import SubscriberForm

hostel_app/templates/booking.html
{% extends "root.html" %}
{% block content %}
<style>
    .booking-form {
        background: linear-gradient(to top right, #ffffcc 11%, #999966 100%);
    border-radius: 5px;
    padding: 20px;
    margin-bottom: 20px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    max-width: 500px;
    margin: 0 auto;
    margin-top: 50px;
}

.form-input {
    width: 100%;
    padding: 8px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
}



.booking-info {
    background-color: #ffffff;
    border-radius: 5px;
    padding: 10px;
    margin-top: 10px;
}

.booking-info p {
    margin: 5px 0;
}

</style>
    <div class="booking-form">
        <h2>Забронировать номер</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" value="Отправить" type="submit">
        </form>
        
        {% for booking in bookings_list %} 
            <div class="booking-info">
                <p>{{ booking.name }}</p>
                <p>{{ booking.phone }}</p>
                <p>{{ booking.room }}</p>
                <p>{{ booking.num_of_guest }}</p>
                <p>{{ booking.num_of_child }}</p>
                <p>{{ booking.checkin_date }}</p>
                <p>{{ booking.checkout_date }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

hostel_app/templates/confirmation.html
{% extends "root.html" %}
{% block content %}
<h3>Вы успешно забронировали места на: <h1>{{ event.title }}</h1></h3>
<h4>Оплата бронирования</h4>
<p>Сумма к оплате: {{ event.price }} за один билет</p>
<img src="/static/images/qr.jpg" style="height: 200px;">
<a href="{% url 'main:profile_user' %}">Перейти в профиль</a>
{% endblock %}

hostel_app/templates/fitness.html
{% extends 'root.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        header h1 {
            overflow: hidden;
            white-space: nowrap;
            animation: running-text 10s linear infinite;
        }
        .blue {
            background-color: lightblue;
            height: 100px;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .trainers-container {
    display: flex;
    justify-content: center;
    gap: 20px;
    margin-top: 20px;
}
.fitness-cards {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px;
    margin-top: 20px;
}

.fitness-card {
    width: 200px;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 10px;
    background-color: #f5f5f5;
    text-align: center;
}

.fitness-card img {
    width: 50px;
    height: 50px;
}

.fitness-card h3 {
    font-size: 18px;
    margin: 10px 0;
    color: #333;
}
.modern {
    background-color: lightblue;
    color: #333; 
    border-radius: 15px; 
    box-shadow: 0 4px 6px rgba(0,0,0,0.1); 
    padding: 20px;
    margin: 10px;
    text-align: center;
}

.trainer-card img {
    width: 100%;
    border-radius: 15px 15px 0 0; /* Закругленные углы только сверху */
}

.trainer-card h3 {
    margin-top: 10px;
}

.trainer-card p {
    font-size: 14px;
}

.trainers-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
}
        @keyframes running-text {
            0% {
                transform: translateX(100%);
            }
            100% {
                transform: translateX(-100%);
            }
        }
    </style>
</head>
<body>
    
    <div class="blue">
        <header>
            <h1>Добро пожаловать в наш фитнес центр!</h1>
        </header>
    </div>
     <!-- Start About -->
	<div class="about-section-box">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12">
					<img src="/static/images/fitness.jpg" alt="" class="img-fluid">
				</div>
				<div class="col-lg-6 col-md-6 col-sm-12 text-center">
					<div class="inner-column">
						<h1>Добро пожаловать в <span>фитнес-центр "SportFit"!</span></h1>
					
						<p>Фитнес-центр "SportFit" - это современный спортивный комплекс с высококлассными тренажерами и индивидуальным подходом к каждому клиенту. Наша команда профессионалов поможет вам достичь ваших спортивных целей, независимо от уровня подготовки.</p>
                        <p>Наши тренеры - это лучшие специалисты в области фитнеса, йоги, кроссфита и других направлений. Они готовы помочь вам создать программу тренировок, которая будет подходить именно вам.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End About -->
    <div class="fitness-cards">
        <div class="fitness-card">
            <img src="/static/images/icon1.png" alt="Icon 2">
            <h3>Кроссфит</h3>
        </div>
        <div class="fitness-card">
            <img src="/static/images/icon2.png" alt="Icon 1">
            <h3>Йога</h3>
        </div>
        
        <div class="fitness-card">
            <img src="/static/images/icon3.png" alt="Icon 2">
            <h3>Кардио-тренировки</h3>
        </div>
        <div class="fitness-card">
            <img src="/static/images/icon4.png" alt="Icon 1">
            <h3>Зумба</h3>
        </div>
        
        <div class="fitness-card">
            <img src="/static/images/icon5.png" alt="Icon 2">
            <h3>Пилатес</h3>
        </div>
        
    </div>
    <div class="d-flex justify-content-center mt-4">
        <h2>Наши тренеры:</h2>
    </div>
    <div class="trainers-container">
        <div class="trainer-card modern">
            <img src="/static/images/trainer1.jpg" style="width: 300px;height: 200px;" alt="Trainer 1">
            <h3>Иванова Анна</h3>
            <p>Сертифицированный тренер по кроссфиту</p>
        </div>
        <div class="trainer-card modern">
            <img src="/static/images/trainer2.png" style="width: 300px;height: 200px;" alt="Trainer 2">
            <h3>Петров Дмитрий</h3>
            <p>Инструктор по йоге</p>
        </div>
        <div class="trainer-card modern">
            <img src="/static/images/trainer3.jpg" style="width: 300px;height: 200px;" alt="Trainer 3">
            <h3>Соколова Елена</h3>
            <p>Тренер по кардио-тренировкам</p>
        </div>
        <div class="trainer-card modern">
            <img src="/static/images/trainer4.jpg" style="width: 300px;height: 200px;" alt="Trainer 4">
            <h3>Козлов Игорь</h3>
            <p>Инструктор по зумбе</p>
        </div>
    </div>    
</body>
</html>
{% endblock %}

hostel_app/templates/rooms2.html
{% extends "root.html" %}
<!DOCTYPE html>
<html lang="en">
    <head>
   
    </head>
    <body>
    {% block content %}
    <div class="cards">
        <div class="d-flex justify-content-end" style="margin-right: 20px; margin-top: 20px;">
            <form action="." method='get'>
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-primary" style="width: 80px;height: 30px; font-size: 12px; display: flex; align-items: center; justify-content: center;">Поиск</button>
            </form>
        </div>
    <!-- Room Start -->
    <div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title text-center text-primary text-uppercase">Номера</h6>
            <h1 class="mb-5">Выберите <span class="text-primary text-uppercase">Номер</span></h1>
        </div>
  
        
           
   
    <div class="two" style="display: flex; justify-content: space-around;">  
      {% for room2 in rooms %}  
             
    <div class="card" style="width: 18rem;"> 
      <img src={{ room2.img.url }} class="card-img-top" width="200px" height="200px" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{ room2.name }}</h5>
        <p class="truncate-text" >{{ room2.description|truncatechars:80}}</p>  
        <a href="{% url 'hostel_app:details' room2.pk %}" class="btn btn-primary">Подробнее</a>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="d-flex justify-content-center mt-4">
    <nav aria-label="Page navigation example">
    <ul class="pagination">
        {% for i in paginator.page_range %}
        <li class="page-item">
            {% if i == rooms.number %}
                {{i}}
            {% else %}
            <a class="page-link" href="{% url 'hostel_app:rooms' %}?page={{i}}">{{i}}</a>
            {% endif %}
        </li>
        {% endfor %}

  
        <li class="page-item">
            {% if rooms.has_previous %}
            <a class="page-link" href="{% url 'hostel_app:rooms' %}?page={{ rooms.previous_page_number }}">⇺</a>
            {% endif %}
        </li>
        <li class="page-item">{{ rooms.number }}</li>
        
        <li class="page-item">
             {% if rooms.has_next %}
             <a class="page-link" href="{% url 'hostel_app:rooms' %}?page={{ rooms.next_page_number }}">⤘</a>
             {% endif %}
         </li>
          
    </ul>
    
    </div>
    {% endblock %}  
</nav>
</div>
    </body>
</html>  

hostel_app/templates/rooms_details.html
{% extends "root.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
   
    </head>
    <body>
    {% block content %}
    <div class="s0">
<img src={{ pk.img.url }}  width="700" alt="...">

<div class="s1">
  <h1><b>Название:</b> {{ pk.name }}</h1>

 <h4><b>Описание:</b> {{ pk.description }}</h1>
 <h4><b>Цена:</b> {{ pk.price }}</h1>
 <h4><b>Рейтинг:</b><img src="/static/images/rating.png" width="60px"></h1>
 </div>
 </div>

      

    {% endblock %} 
    </body>
</html>

hostel_app/templates/subscribed.html
{% extends "root.html" %}
{% block content %}
<h1 class="mt-5">Thank you for subscribing!</h1>
{% endblock %}