api/urls.py
from django.urls import path
from rest_framework import routers
from .views import ProductViewSet, ContractorViewSet, OperationViesSet, StorageItemViewSet, DocumentViewSet, \
    DocumentItemViewSet, contractor_categories, apply_document, unapply_document, remove_marked_objects, \
    import_products, consolidated_report, motion_report

app_name = 'api'

urlpatterns = [
    path('contractor_categories/', contractor_categories, name='contractor_categories'),
    path('apply_document/<int:document_id>/', apply_document, name='apply_document'),
    path('unapply_document/<int:document_id>/', unapply_document, name='unapply_document'),
    path('remove_marked_objects/', remove_marked_objects, name='remove_marked_objects'),
    path('import_products/', import_products, name='import_products'),
    path('consolidated_report/', consolidated_report, name='consolidated_report'),
    path('motion_report/', motion_report, name='motion_report')
]

router = routers.SimpleRouter()
router.register('products', ProductViewSet, basename='products')
router.register('contractors', ContractorViewSet, basename='contractors')
router.register('operations', OperationViesSet)
router.register('documents', DocumentViewSet, basename='documents')
router.register('document_items', DocumentItemViewSet, basename='document_items')
router.register('storage_items', StorageItemViewSet, basename='storage_items')
urlpatterns.extend(router.urls)

hostel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main.views import Login, Logout


urlpatterns = [
    path('admin/', admin.site.urls),
    path("hostel_app/", include("hostel_app.urls", namespace="hostel_app")),
    path('accounts/',include('allauth.urls')),
    #path('restaurant/', include('hostel_app.urls', namespace='restaurant'))
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('api/', include('api.urls')),
    path('storage', include('main.urls'))
   
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

hostel_app/urls.py
from django.urls import path
from hostel_app.views import HostelAppView, HostelAppView2, restaurant_view, room_id_view
from . import views


app_name = 'hostel_app'

urlpatterns=[
    path('', HostelAppView.as_view(), name='hostel_app'),
    path('room/', HostelAppView2.as_view(), name='rooms'),
    path('booking/', views.book_room, name='booking'),
    path('fitness/', views.fitness_view, name='fitness'),
    path('restaurant/', restaurant_view, name='restaurant'),
    path('<int:pk>/', room_id_view, name='details'),
    path('profile_user/',  views.view_profile, name='profile_user'),
    path('profile_user/edit_profile/', views.edit_profile, name='edit_profile'),
    path('profile_user/create_profile/', views.create_profile, name='create_profile'),
    path('profile_user/create_profile/success', views.success, name='success'),
   
]

templates/root.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>"Альянс"</title>
        
        <script src = '{% static "js/bootstrap.min.js" %}'></script>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <!-- Libraries Stylesheet -->
        <link href="/static/lib/animate/animate.min.css" rel="stylesheet">
        <link href="/static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="/static/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />
       
<!-- Site Icons -->
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
<link rel="apple-touch-icon" href="images/apple-touch-icon.png">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="/static/css/bootstrap.min.css">    

<link rel="stylesheet" href="/static/css/style.css">    
<!-- Responsive CSS -->
<link rel="stylesheet" href="/static/css/responsive.css">
<!-- Custom CSS -->
<link rel="stylesheet" href="/static/css/custom.css">

 <!--[if lt IE 9]>
   <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
   <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
 <![endif]-->


<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
         <style>
            .off-link-decoration {
                text-decoration: none;
                color: black;
            }

            .active .off-link-decoration {
                color: white;
            }

            .off-link-decoration:hover {
                text-decoration: none;
            }
            .auth{

                display: flex;
                align-items: center;}

              
        </style>
    </head>
        <body>
  
            <!-- Header Start -->
                <div class="container-fluid bg-dark px-0">
                    <div class="row gx-0">
                        <div class="col-lg-3 bg-dark d-none d-lg-block">
                            <a href="http://127.0.0.1:8000/hostel_app/" class="navbar-brand w-100 h-100 m-0 p-0 d-flex align-items-center justify-content-center">
                                <h1 class="m-0 text-primary text-uppercase">Альянс</h1>
                            </a>
                        </div>
                        <div class="col-lg-9">
                            <div class="row gx-0 bg-white d-none d-lg-flex">
                                <div class="col-lg-7 px-5 text-start">
                                    <div class="h-100 d-inline-flex align-items-center py-2 me-4">
                                        <i class="fa fa-envelope text-primary me-2"></i>
                                        <p class="mb-0">Alyans23@gmail.com</p>
                                    </div>
                                    <div class="h-100 d-inline-flex align-items-center py-2">
                                        <i class="fa fa-phone-alt text-primary me-2"></i>
                                        <p class="mb-0">+012 345 67890</p>
                                    </div>
                                </div>
                                <div class="col-lg-5 px-5 text-end">
                                    <div class="d-inline-flex align-items-center py-2">
                                        <a class="me-3" href=""><i class="fab fa-facebook-f"></i></a>
                                        <a class="me-3" href=""><i class="fab fa-twitter"></i></a>
                                        <a class="me-3" href=""><i class="fab fa-linkedin-in"></i></a>
                                        <a class="me-3" href=""><i class="fab fa-instagram"></i></a>
                                        <a class="" href=""><i class="fab fa-youtube"></i></a>
                                    </div>
                                </div>
                            </div>
                            <nav class="navbar navbar-expand-lg bg-dark navbar-dark p-3 p-lg-0">
                                <a href="http://127.0.0.1:8000/hostel_app/" class="navbar-brand d-block d-lg-none">
                                    
                                </a>
                                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                                    <div class="navbar-nav mr-auto py-0">
                                        <a href="http://127.0.0.1:8000/hostel_app/" class="nav-item nav-link active">Главная</a>
                                        <a href="http://127.0.0.1:8000/hostel_app/#mb-4" class="nav-item nav-link">О нас</a>
                                        <a href="http://127.0.0.1:8000/hostel_app/#container-xxl py-5" class="nav-item nav-link">Услуги</a>
                                        <a href="{% url 'hostel_app:rooms' %}" class="nav-item nav-link">Номера</a>
                                        <a href="{% url 'hostel_app:restaurant' %}" class="nav-item nav-link">Ресторан</a>
                                        {% if user.is_authenticated %}
                                        <a href="{% url 'hostel_app:booking' %}" class="nav-item nav-link">Бронирование</a>
                                        {% endif %}
                                     <div class="auth">
                                     {% if user.is_authenticated %}
                                           <span>{{ user.username }}</span>
                                           <a href="{% url 'account_logout' %}"
                                              style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">
                                               Выход
                                           </a>
                                       {% else %}
                                           <a href="{% url 'account_login' %}"
                                              style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">
                                               Вход
                                           </a>
                                           /
                                            <a href="{% url 'account_signup' %}"
                                              style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">
                                               Регистрация
                                           </a>
                                       {% endif %}
                                       </div>
                                    </div>
                                    
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
                <!-- Header End -->

              
                <div class="content">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
 
        </div>
  <!-- Footer Start -->
  <div class="container-fluid bg-dark text-light footer wow fadeIn" data-wow-delay="0.1s">
      <div class="container pb-5">
          <div class="row g-5">
              
              <div class="col-md-6 col-lg-3">
                  <h6 class="section-title text-start text-primary text-uppercase mb-4">Contact</h6>
                  <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, Kurgan, Russia</p>
                  <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                  <p class="mb-2"><i class="fa fa-envelope me-3"></i>Alyans23@gmail.com</p>
                  <div class="d-flex pt-2">
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                      <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                  </div>
              </div>
              <div class="col-lg-5 col-md-12">
                  <div class="row gy-5 g-4">
                      <div class="col-md-6">
                          <h6 class="section-title text-start text-primary text-uppercase mb-4">Company</h6>
                          <a class="btn btn-link" href="http://127.0.0.1:8000/hostel_app/#mb-4">О нас</a>
                          
                   
                      </div>
                      <div class="col-md-6">
                          <h6 class="section-title text-start text-primary text-uppercase mb-4">Services</h6>
                          <a class="btn btn-link" href="{% url 'hostel_app:restaurant' %}">Ресторан</a>
                          <a class="btn btn-link" href="{% url 'hostel_app:fitness' %}">Фитнес</a>
              
                      </div>
                      
                  </div>
              </div>
          </div>
      </div>
      <div class="container">
          <div class="copyright">
              <div class="row">
                
                  <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                      &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved. 
	
	<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
	Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                  </div>
                
                  <div class="col-md-6 text-center text-md-end">
                      <div class="footer-menu">
                          <a href="">Главная</a>
                          <a href="">Cookies</a>
                          <a href="">Помощь</a>
                          
                      </div>
                      
                  </div>
                  
              </div>
             
          </div>
      </div>
  </div>
  <!-- Footer End -->

        </body>
    </html>