api/urls.py
from django.urls import path
from rest_framework import routers
from .views import ProductViewSet, ContractorViewSet, OperationViesSet, StorageItemViewSet, DocumentViewSet, \
    DocumentItemViewSet, contractor_categories, apply_document, unapply_document, remove_marked_objects, \
    import_products, consolidated_report, motion_report

app_name = 'api'

urlpatterns = [
    path('contractor_categories/', contractor_categories, name='contractor_categories'),
    path('apply_document/<int:document_id>/', apply_document, name='apply_document'),
    path('unapply_document/<int:document_id>/', unapply_document, name='unapply_document'),
    path('remove_marked_objects/', remove_marked_objects, name='remove_marked_objects'),
    path('import_products/', import_products, name='import_products'),
    path('consolidated_report/', consolidated_report, name='consolidated_report'),
    path('motion_report/', motion_report, name='motion_report')
]

router = routers.SimpleRouter()
router.register('products', ProductViewSet, basename='products')
router.register('contractors', ContractorViewSet, basename='contractors')
router.register('operations', OperationViesSet)
router.register('documents', DocumentViewSet, basename='documents')
router.register('document_items', DocumentItemViewSet, basename='document_items')
router.register('storage_items', StorageItemViewSet, basename='storage_items')
urlpatterns.extend(router.urls)

hostel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main.views import Login, Logout


urlpatterns = [
    path('admin/', admin.site.urls),
    path("hostel_app/", include("hostel_app.urls", namespace="hostel_app")),
    path('accounts/',include('allauth.urls')),
    #path('restaurant/', include('hostel_app.urls', namespace='restaurant'))
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('api/', include('api.urls')),
    path('storage', include('main.urls'))
   
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import index, products, contractors, documents, operations, storage_items, products_to_xls, \
    contractors_to_xls, remove_marked_objects, import_products, consolidated_report, motion_report

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('products/', products, name='products'),
    path('contractors/', contractors, name='contractors'),
    path('documents/', documents, name='documents'),
    path('operations/', operations, name='operations'),
    path('storage_items/', storage_items, name='storage_items'),
    path('products_to_xls/', products_to_xls, name='products_to_xls'),
    path('contractors_to_xls/', contractors_to_xls, name='contractors_to_xls'),
    path('remove_marked_objects/', remove_marked_objects, name='remove_marked_objects'),
    path('import_products/', import_products, name='import_products'),
    path('consolidated_report/', consolidated_report, name='consolidated_report'),
    path('motion_report/', motion_report, name='motion_report')
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class Token(models.Model):
    token = models.CharField(max_length=32, verbose_name='Токен')
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return f'Токен {self.token} для пользователя {self.user}'

    class Meta:
        verbose_name = 'Токен пользователя'
        verbose_name_plural = 'Токены пользователей'


class BaseDataModel(models.Model):
    dt_created = models.DateTimeField(verbose_name='Дата и время создания', auto_now_add=True)
    dt_updated = models.DateTimeField(verbose_name='Дата и время последнего изменения', auto_now=True)
    to_remove = models.BooleanField(verbose_name='Помечен на удаление', null=False, default=False)
    
    class Meta:
        abstract = True


class Product(BaseDataModel):
    title = models.CharField(max_length=200, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание', null=True, blank=True, default='')
    price = models.IntegerField(verbose_name='Цена')

    def __str__(self):
        return '{number:<10}|{title}'.format(number=self.pk, title=self.title)

    class Meta:
        verbose_name = 'Инвентарь'
        verbose_name_plural = 'Инвентарь'
        ordering = ['title']


class Contractor(BaseDataModel):
    INDIVIDUAL = 'individual'
    ENTITY = 'entity'

    CONTRACTOR_CATEGORY = (
        (INDIVIDUAL, 'Физическое лицо'),
        (ENTITY, 'Юридическое лицо')
    )

    title = models.CharField(max_length=200, verbose_name='Наименование')
    category = models.CharField(max_length=20, choices=CONTRACTOR_CATEGORY, verbose_name='Категория')

    def __str__(self):
        return '{number:<10}|{title}'.format(number=self.pk, title=self.title)

    class Meta:
        verbose_name = 'Контрагент'
        verbose_name_plural = 'Контрагенты'
        ordering = ['title']


class Operation(models.Model):
    username = models.CharField(max_length=200, verbose_name='Пользователь', null=True, blank=True)
    operation = models.TextField(verbose_name='Операция')
    dt_created = models.DateTimeField(verbose_name='Дата и время операции', auto_now_add=True)

    class Meta:
        verbose_name = 'Операция'
        verbose_name_plural = 'Операции'
        ordering = ['-dt_created']


class StorageItem(BaseDataModel):
    product = models.OneToOneField(Product, on_delete=models.PROTECT, verbose_name='Инвентарь')
    count = models.IntegerField(verbose_name='Количество')

    def __str__(self):
        return f'{str(self.product)} ({self.count})'

    class Meta:
        verbose_name = 'Инвентарь на складе'
        verbose_name_plural = 'Инвентарь на складе'


class Document(BaseDataModel):
    RECEIPT = 'receipt'
    EXPENSE = 'expense'

    DESTINATION_TYPES = (
        (RECEIPT, 'Приход'),
        (EXPENSE, 'Расход')
    )

    destination_type = models.CharField(max_length=7, choices=DESTINATION_TYPES, verbose_name='Тип документа')
    contractor = models.ForeignKey(Contractor, on_delete=models.PROTECT, verbose_name='Контрагент')
    apply_flag = models.BooleanField(verbose_name='Документ проведен', default=False)

    def __str__(self):
        return f'{self.pk} от: {str(self.dt_created)[:19]}'

    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'
        ordering = ['-dt_created']


class DocumentItem(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE, verbose_name='Документ')
    product = models.ForeignKey(Product, on_delete=models.PROTECT, verbose_name='Инвентарь')
    count = models.IntegerField(verbose_name='Количество')

    def __str__(self):
        return f'{self.product.title}. Количество {self.count}'

    class Meta:
        verbose_name = 'Инвентарь в документе'
        verbose_name_plural = 'Инвентарь в документе'

main/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.http.response import FileResponse
from .models import Product, Contractor, Token
from utils import model_to_xls
from django.http import HttpResponse
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
import pandas as pd


class Login(LoginView):
    template_name = 'main/login.html'

    def get_success_url(self):
        user = self.request.user
        token = self.request.POST['user_token']
        Token.objects.update_or_create(user=user, defaults={'token': token})
        return super(Login, self).get_success_url()


class Logout(LogoutView):
    next_page = reverse_lazy('main:index')


@login_required(login_url='login')
def index(request):
    return render(request, 'main/index.html', context={})


@login_required(login_url='login')
def products(request):
    return render(request, 'main/products.html', context={})


@login_required(login_url='login')
def contractors(request):
    return render(request, 'main/contractors.html', context={})


@login_required(login_url='login')
def documents(request):
    return render(request, 'main/documents.html', context={})


@login_required(login_url='login')
def operations(request):
    return render(request, 'main/operations.html', context={})


@login_required(login_url='login')
def storage_items(request):
    return render(request, 'main/storage_items.html', context={})


@login_required(login_url='login')
def products_to_xls(request):
    column_descriptions = [
        {'machine_name': 'id', 'display_name': 'Номер'},
        {'machine_name': 'title', 'display_name': 'Наименование', 'width': 80},
        {'machine_name': 'description', 'display_name': 'Описание', 'width': 30},
        {'machine_name': 'price', 'display_name': 'Цена'},
        {'machine_name': 'dt_created', 'display_name': 'Дата создания', 'width': 30},
        {'machine_name': 'dt_updated', 'display_name': 'Дата изменения', 'width': 30},
    ]
    
    products = Product.objects.all()
    for product in products:
        product.dt_created = product.dt_created.replace(tzinfo=None)
        product.dt_updated = product.dt_updated.replace(tzinfo=None)
    
    df = pd.DataFrame(list(products.values()))
    # Remove timezone information
    df['dt_created'] = df['dt_created'].dt.tz_localize(None)
    df['dt_updated'] = df['dt_updated'].dt.tz_localize(None)
    
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=products.xlsx'
    
    wb = Workbook()
    ws = wb.active
    ws.append([x['display_name'] for x in column_descriptions])
    
    for row in dataframe_to_rows(df, index=False, header=False):
        ws.append(row)
        
    wb.save(response)
    
    return response
   


@login_required(login_url='login')
def contractors_to_xls(request):
    column_descriptions = [
        {'machine_name': 'id', 'display_name': 'Номер'},
        {'machine_name': 'title', 'display_name': 'Наименование', 'width': 80},
        {'machine_name': 'category', 'display_name': 'Категория', 'width': 30,
         'subs': dict(Contractor.CONTRACTOR_CATEGORY)},
        {'machine_name': 'dt_created', 'display_name': 'Дата создания', 'width': 30},
        {'machine_name': 'dt_updated', 'display_name': 'Дата изменения', 'width': 30},
    ]
    
    contractors = Contractor.objects.all()
    for contractor in contractors:
        contractor.dt_created = contractor.dt_created.replace(tzinfo=None)
        contractor.dt_updated = contractor.dt_updated.replace(tzinfo=None)
    
    df = pd.DataFrame(list(contractors.values()))
    # Remove timezone information
    df['dt_created'] = df['dt_created'].dt.tz_localize(None)
    df['dt_updated'] = df['dt_updated'].dt.tz_localize(None)
    
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = 'attachment; filename=contractors.xlsx'
    
    wb = Workbook()
    ws = wb.active
    ws.append([x['display_name'] for x in column_descriptions])
    
    for row in dataframe_to_rows(df, index=False, header=False):
        ws.append(row)
        
    wb.save(response)
    
    return response

@login_required(login_url='login')
def remove_marked_objects(request):
    return render(request, 'main/remove_marked_objects.html', context={})


@login_required(login_url='login')
def import_products(request):
    return render(request, 'main/import_products.html', context={})


@login_required(login_url='login')
def consolidated_report(request):
    return render(request, 'main/consolidated_report.html', context={})


@login_required(login_url='login')
def motion_report(request):
    report_type = request.GET['report_type']
    return render(request, 'main/motion_report.html', context={'report_type': report_type})

main/templates/main/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'main/base.css' %}">
    <link rel="stylesheet" href="{% static 'main/menu.css' %}">
    <link rel="stylesheet" href="{% static 'main/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'main/modals.css' %}">
    <link rel="stylesheet" href="{% static 'main/inputs.css' %}">
    <link rel="stylesheet" href="{% static 'main/content.css' %}">
    <link rel="stylesheet" href="{% static 'main/login.css' %}">
    <link rel="stylesheet" href="{% static 'main/search_elements.css' %}">
    <script src="{% static 'main/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'main/common.js' %}"></script>
    <title>MiniStorage</title>
</head>
<body>

{% block message %}
{% endblock %}

{% block menu %}
{% endblock %}

{% block content %}
{% endblock %}

{% block modals %}
{% endblock %}

{% block scripts %}
{% endblock %}
</body>
</html>

main/templates/main/consolidated_report.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}
    <div class="basic-div content-div"><strong>Сводный отчет по базе данных</strong></div>
    <div class="basic-div content-div" id="content-div">
        <p>Отправляю запрос на формирование отчета...</p>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const apiConsolidatedReportURL = "/api/consolidated_report/";
        let reportsDescriptions = [
            {
                key: "product_count",
                description: "Общее количество наименований инвентаря в справочнике"
            },
            {
                key: "contractor_count",
                description: "Общее количество наименований контрагентов в справочнике"
            },
            {
                key: "storage_item_count",
                description: "Общее количество наименований инвентаря на складе"
            },
            {
                key: 'total_cost',
                description: "Общая стоимость инвентаря на складе"
            }
        ]

        let $contentDiv = $("#content-div");

        $.ajax(apiConsolidatedReportURL, {
            "method": "GET",
            "dataType": "json",
            "success": function (data) {
                $contentDiv.empty();

                for (let {key, description} of reportsDescriptions) {
                    $contentDiv.append(
                        $("<p>")
                            .addClass("report-block")
                            .append($("<strong>").text(description + ": "))
                            .append($("<span>").text(data[key]))
                    );
                }
            },
            "error": function (jqXHR) {
                $contentDiv.empty();
                showAjaxError(jqXHR);
            }
        });
    </script>
{% endblock %}

main/templates/main/contractors.html
{% extends 'main/index.html' %}
{% load static %}

{% block content %}
    <div class="basic-div content-div"><strong>Справочник контрагентов</strong></div>
    <div class="basic-div content-div" id="content-div">
        <div class="operation-div">
            <span class="span-button" id="create-button">Создать</span>
            <input type="text" name="search-field" id="search-field" value="">
            <span class="span-button" id="search-button">Найти</span>
            <span class="span-button" id="clear-search-field-button">Очистить</span>
        </div>
        <table id="content-table" class="content-table">
            <tr>
                <th column-key="id" display-name="Номер">Номер</th>
                <th column-key="title" display-name="Наименование">Наименование</th>
                <th column-key="category" display-name="Категория">Категория</th>
                <th column-key="dt_created" display-name="Дата создания">Дата создания</th>
                <th column-key="dt_updated" display-name="Дата изменения">Дата изменения</th>
                <th column-key="to_remove" display-name="Удл.">Удл.</th>
            </tr>
        </table>
        <div class="navigation-div">
            <span class="span-button" id="prev-page-button">Предыдущая страница</span>
            <span class="span-button" id="next-page-button">Следующая страница</span>
        </div>
    </div>
{% endblock %}

{% block modals %}
    <div class="modal" id="contractor-editor" style="display: none">
        <div>
            <div class="modal-control-buttons">
                <span class="span-button" id="contractor-editor-close-button">X</span>
            </div>
            <div>
                Номер: <span id="contractor-number"></span><br><br>
                Дата создания: <span id="contractor-dt-created"></span><br><br>
                Дата изменения: <span id="contractor-dt-updated"></span><br><br>
                <fieldset>
                    Наименование:<br><input type="text" name="contractor-title" id="contractor-title" value="" required><br><br>
                    Категория:
                    <select name="contractor-category" id="contractor-category"></select><br><br>
                    Пометить на удаление: <input type="checkbox" name="contractor-to-remove" id="contractor-to-remove">
                </fieldset>
            </div>
            <br>
            <div class="modal-control-buttons">
                <span class="span-button" id="contractor-editor-cancel-button">Отмена</span>
                <span class="span-button" id="contractor-editor-save-button">Сохранить</span>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        const apiURL = "/api/contractors/";

        const apiContractorCategoriesURL = "/api/contractor_categories/";
        let contractorCategories = null;

        function checkContractorFormData() {
            if ($("#contractor-title").val().trim() === "") {
                throw new Error("Наименование не может быть пустым!")
            }
        }

        function showContractors(url) {
            if (!contractorCategories) {
                $.ajax(apiContractorCategoriesURL, {
                    "method": "GET",
                    "dataType": "json",
                    "async": false,
                    "success": function (data) {
                        contractorCategories = data;
                    }
                })
            }
            $.ajax(url, {
                "method": "GET",
                "dataType": "json",
                "success": function (data) {
                    let contractors, nextPage, prevPage;
                    if ("results" in data) {
                        contractors = data.results;
                        nextPage = data.next;
                        prevPage = data.previous;
                    } else {
                        contractors = [data];
                        nextPage = prevPage = null;
                    }

                    //Создаем таблицу со списком контрагентов
                    let $contentTable = $("#content-table");
                    $("tr:not(:first-child)", $contentTable).remove()
                    let $tableRow = null;
                    for (let contractor of contractors) {
                        formatDates(contractor);
                        $tableRow = $("<tr>");
                        $tableRow.append($("<td>").text(contractor.id));
                        $tableRow.append($("<td>").text(contractor.title));
                        $tableRow.append($("<td>").text(contractorCategories[contractor.category]));
                        $tableRow.append($("<td>").text(contractor.dt_created));
                        $tableRow.append($("<td>").text(contractor.dt_updated));
                        $tableRow.append($("<td>").text(contractor.to_remove ? "X" : "-"));
                        $tableRow.data("contractor", contractor);
                        $contentTable.append($tableRow);
                    }
                    $contentTable.on("click", "tr:not(:first-child)", contractorEdit);

                    createPaginationButtons(prevPage, nextPage, showContractors);
                },
                "error": function (jqXHR) {
                    showAjaxError(jqXHR, $("#contractor-editor"));
                }
            })
        }

        function contractorEdit() {
            let selectedContractor = $.data(this, "contractor");

            let $row = $(this);

            showModal($("#contractor-editor"));
            $("#contractor-number").text(selectedContractor.id);
            $("#contractor-dt-created").text(selectedContractor.dt_created);
            $("#contractor-dt-updated").text(selectedContractor.dt_updated);
            $("#contractor-title").val(selectedContractor.title);
            let categoriesList = [];
            for (let [key, value] of Object.entries(contractorCategories)) {
                categoriesList.push($("<option>").val(key).text(value));
                if (key === selectedContractor.category) {
                    categoriesList[categoriesList.length - 1].prop("selected", true);
                }
            }
            $("#contractor-category").empty().append(...categoriesList);
            $("#contractor-to-remove").prop("disabled", false);
            $("#contractor-to-remove").prop("checked", selectedContractor.to_remove);

            $("#contractor-editor-save-button").off().click(() => {
                //Проверяем корректность внесения данных в форму
                try {
                    checkContractorFormData();
                } catch (error) {
                    alert(error.message);
                    return;
                }

                let urlForRequest = `${apiURL}${selectedContractor.id}/`;
                $.ajax(urlForRequest, {
                    "method": "PATCH",
                    "dataType": "json",
                    "data": {
                        "title": $("#contractor-title").val(),
                        "category": $("#contractor-category").val(),
                        "to_remove": $("#contractor-to-remove:checked").val() ? true : false
                    },
                    "success": function (data) {
                        formatDates(data);

                        $row.empty();
                        $row.append($("<td>").text(data.id));
                        $row.append($("<td>").text(data.title));
                        $row.append($("<td>").text(contractorCategories[data.category]));
                        $row.append($("<td>").text(data.dt_created));
                        $row.append($("<td>").text(data.dt_updated));
                        $row.append($("<td>").text(data.to_remove ? "X" : "-"));
                        $row.data("contractor", data);

                        closeModal($("#contractor-editor"));
                    },
                    "error": function (jqXHR) {
                        showAjaxError(jqXHR, $("#contractor-editor"));
                    }
                })
            })
        }

        function contractorCreate() {
            showModal($("#contractor-editor"));

            $("#contractor-number").text("-");
            $("#contractor-dt-created").text("-");
            $("#contractor-dt-updated").text("-");
            $("#contractor-title").val("");
            let categoriesList = [];
            for (let [key, value] of Object.entries(contractorCategories)) {
                categoriesList.push($("<option>").val(key).text(value));
            }
            categoriesList[0].prop("selected", true);
            $("#contractor-category").empty().append(...categoriesList);
            $("#contractor-to-remove").prop("disabled", true);
            $("#contractor-to-remove").prop("checked", false);

            $("#contractor-editor-save-button").off().click(() => {
                try {
                    checkContractorFormData();
                } catch (error) {
                    alert(error.message);
                    return
                }

                $.ajax(apiURL, {
                    "method": "POST",
                    "dataType": "json",
                    "data": {
                        "title": $("#contractor-title").val(),
                        "category": $("#contractor-category").val()
                    },
                    "success": function (data) {
                        closeModal($("#contractor-editor"));
                        $("#search-field").val(data.id);
                        showContractors(`${apiURL}${data.id}`);
                    },
                    "error": function (jqXHR) {
                        showAjaxError(jqXHR, $("#contractor-editor"));
                    }
                })
            })
        }

        let contractorSearch = getSearchFunction(showContractors, getDefaultSearchParams, apiURL);

        let contractorSort = getSortFunction(showContractors, getDefaultSearchParams, apiURL);

        $("#clear-search-field-button").click(() => {
            $("#search-field").val("");
            contractorSearch();
        });
        $("#create-button").click(contractorCreate);
        $("#search-button").click(contractorSearch);
        $("#contractor-editor-close-button, #contractor-editor-cancel-button").click(() => closeModal($("#contractor-editor")));
        $("#content-table th").click(contractorSort);

        showContractors(apiURL);
    </script>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base_template.html' %}
{% load static %}

{% block message %}
    <div class="modal" id="message-block" style="display: none">
        <div>
            <div class="modal-control-buttons">
                <span class="span-button" id="message-block-close-button">X</span>
            </div>
            <div>
                <p></p>
            </div>
            <div class="modal-control-buttons">
                <span class="span-button" id="message-block-ok-button">Ок</span>
            </div>
        </div>
    </div>

    <script>
        $("#message-block-close-button, #message-block-ok-button").click(() => {
            closeModal($("#message-block"))
        });
    </script>
{% endblock %}

{% block menu %}
    <div id="header">
        <div class="basic-div">
            <ul id="menu">
                <li>
                <span>
                    {% if user.first_name or user.last_name %}
                        {{ user.get_full_name }}
                    {% else %}
                        {{ user }}
                    {% endif %}
                </span>
                    <ul>
                        <li>
                        <span>
                            <a href="{% url 'logout' %}">Выйти</a>
                        </span>
                        </li>
                    </ul>
                </li>
                <li>
                    <span>Справочники</span>
                    <ul>
                        <li>
                            <span>
                                <a href="{% url 'main:products' %}">Инвентарь</a>
                            </span>
                        </li>
                        <li>
                            <span>
                                <a href="{% url 'main:contractors' %}">Контрагенты</a>
                            </span>
                        </li>
                    </ul>
                </li>
                <li>
                    <span>
                        <a href="{% url 'main:documents' %}">Документы</a>
                    </span>
                </li>
                <li>
                    <span>Отчеты</span>
                    <ul>
                        <li>
                            <span>
                                <a href="{% url 'main:consolidated_report' %}">Сводный отчет по базе данных</a>
                            </span>
                        </li>
                        <li>
                            <span>
                                <a href="{% url 'main:motion_report' %}?report_type=products">Отчет по движениям инвентаря</a>
                            </span>
                        </li>
                        <li>
                            <span>
                                <a href="{% url 'main:motion_report' %}?report_type=contractors">Отчет по операциям с контрагентами</a>
                            </span>
                        </li>
                        <li>
                            <span>
                                <a href="{% url 'main:products_to_xls' %}">Список инвентаря (XLS)</a>
                            </span>
                        </li>
                        <li>
                            <span>
                                <a href="{% url 'main:contractors_to_xls' %}">Список контрагентов (XLS)</a>
                            </span>
                        </li>
                    </ul>
                </li>
                <li>
                    <span>Сервис</span>
                    <ul>
                        {% if user.is_superuser %}
                            <li>
                                <span>
                                    <a href="/admin/">Администрирование</a>
                                </span>
                            </li>
                            <li>
                                <span>
                                    <a href="{% url 'main:remove_marked_objects' %}">Удаление помеченных объектов</a>
                                </span>
                            </li>
                            <li>
                                <span>
                                    <a href="{% url 'main:import_products' %}">Импорт инвенатря</a>
                                </span>
                            </li>
                            <li>
                                <span>
                                    <a href="{% url 'main:storage_items' %}">Управление остатками</a>
                                </span>
                            </li>
                        {% else %}
                            <li>
                                <span>
                                    <a href="{% url 'main:storage_items' %}">Просмотр остатков</a>
                                </span>
                            </li>
                        {% endif %}
                        <li>
                            <span>
                                <a href="{% url 'main:operations' %}">Журнал операций</a>
                            </span>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>

{% endblock %}